name: Run tests and checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Test with pytest
        run: |
          pip install pytest
          pytest

      - name: Test with doctest
        run: |
          pip install sphinx sphinx-rtd-theme
          cd docs
          make doctest

      - name: Check with ruff linter
        run: |
          pip install ruff
          ruff check src

      - name: Check with ruff formatter
        run: |
          ruff format --check src
